import './base.css';
import './cluster.css';
import './job.css';
import './clusterDetails.css';
import './submitJob.css';
import './batches.css';
import './authLogin.css';
import './sessionDetails.css';
import './popup.css'
import './dpms.css'
import './databaseInfo.css'
